"""
Django settings for sdc4 project.

Generated by SDCStudio AppGen (Enterprise Stack).
"""

import importlib
from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _discover_local_apps():
    """Auto-discover installed DM apps by scanning for directories with apps.py."""
    from django.apps import AppConfig as _AppConfig
    _skip = {
        'api', 'core', 'generic_storage', 'sdc4_shared',
        'templates', 'staticfiles', 'mediafiles', 'ontologies',
        Path(__file__).resolve().parent.name,  # project config package
    }
    discovered = []
    for entry in sorted(BASE_DIR.iterdir()):
        if not entry.is_dir() or entry.name in _skip:
            continue
        if entry.name.startswith('.') or entry.name.startswith('_'):
            continue
        if not (entry / 'apps.py').exists():
            continue
        try:
            mod = importlib.import_module(f'{entry.name}.apps')
            if any(
                isinstance(getattr(mod, attr, None), type)
                and issubclass(getattr(mod, attr), _AppConfig)
                and getattr(mod, attr) is not _AppConfig
                for attr in dir(mod)
            ):
                discovered.append(entry.name)
        except Exception:
            pass
    return discovered


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-sdc4-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'django_htmx',
    'widget_tweaks',

    # Authentication (Keycloak SSO)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',

    # Project apps
    'core',  # Management commands and utilities
    'generic_storage',  # File storage backend
    'api',  # REST API endpoints
] + _discover_local_apps()

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'sdc4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sdc4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Celery Configuration
# https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# =============================================================================
# Enterprise Stack Configuration
# =============================================================================

# GraphDB Configuration (OWL 2 Reasoning Triplestore)
# Replaces Apache Fuseki in the lightweight stack
GRAPHDB_URL = config('GRAPHDB_URL', default='http://localhost:17200')
GRAPHDB_REPOSITORY = config('GRAPHDB_REPOSITORY', default='sdc4_rdf')
GRAPHDB_USER = config('GRAPHDB_USER', default='admin')
GRAPHDB_PASSWORD = config('GRAPHDB_PASSWORD', default='admin123')

# SirixDB Configuration (Temporal JSON/XML Database)
# Provides time-travel queries and temporal versioning
SIRIX_URL = config('SIRIX_URL', default='https://localhost:9443')
SIRIX_USER = config('SIRIX_USER', default='admin')
SIRIX_PASSWORD = config('SIRIX_PASSWORD', default='admin123')
SIRIX_DATABASE = config('SIRIX_DATABASE', default='sdc4_temporal')
# Disable SSL verification for local development (SirixDB uses self-signed certs)
SIRIX_VERIFY_SSL = config('SIRIX_VERIFY_SSL', default=False, cast=bool)

# Keycloak Configuration (SSO/RBAC Authentication)
# Provides OAuth2, OIDC, and SAML 2.0 support
KEYCLOAK_URL = config('KEYCLOAK_URL', default='http://localhost:8080')
KEYCLOAK_REALM = config('KEYCLOAK_REALM', default='sdc4')
KEYCLOAK_CLIENT_ID = config('KEYCLOAK_CLIENT_ID', default='sdc4-web')
KEYCLOAK_CLIENT_SECRET = config('KEYCLOAK_CLIENT_SECRET', default='changeme')

# Django Sites Framework (required for django-allauth)
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Django-Allauth Configuration
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Keycloak handles email verification
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Keycloak OIDC Provider Configuration (django-allauth)
SOCIALACCOUNT_PROVIDERS = {
    'openid_connect': {
        'APPS': [
            {
                'provider_id': 'keycloak',
                'name': 'Keycloak',
                'client_id': KEYCLOAK_CLIENT_ID,
                'secret': KEYCLOAK_CLIENT_SECRET,
                'settings': {
                    'server_url': f'{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}/.well-known/openid-configuration',
                },
            },
        ],
    },
}

# Enterprise Stack Indicator
SDC4_STACK = config('SDC4_STACK', default='enterprise')
